version: "3.9"
services:
  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile.dev
    image: myapp-server
    deploy:
      resources: # Set these values when you know what you do!
        limits:
          cpus: "0.5"
          memory: 50M
        reservations:
          cpus: "0.25"
          memory: 20M
    ports:
      - "80:80" # Connect localhost 80 port to container 80 port
    links: # Link services to access http://app and  http://api inside the container
      - api:api
  api:
    deploy:
      resources: # Set these values when you know what you do!
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile.dev
    image: myapp-api
    environment:
      - DB_NAME=myappdb
      - DB_USER=myappuser
      - DB_PASSWORD=myapppassword
      - DB_HOST=dbhost
      - DB_PORT=5432
      - NODE_ENV=dev
    links:
      - db:dbhost
    volumes:
      - ./../api:/usr/src/api
    ports:
      - "8080"
    depends_on:
      - "db"

  db:
    build:
      context: ../.
      dockerfile: docker/db/Dockerfile.dev
    env_file: db/psql.env
    image: myapp-db
    ports:
      - "5431:5432"
